//OBJECT --property and method
//string -- object-- property and method

let fullname= "chinmay";
let rollno= 12;
let isadult= true;

console.log(typeof fullname);
console.log(typeof rollno);
console.log(typeof isadult);

//object
//bank -- object
//property -- account number. acc name , balance
//method -- deposit () savings()

//human
//property -- age, weight, colour,=
//method  talk() walk()

let city = "PUNE";
//city will be property and method

//length
// 0 1 2 3
// P U N E

let aaa= city.length;
console.log(aaa);
 
let city2="NAGPUR";
let bbb=city2.length;
console.log(city2.length);

let city3="PUNE";

// 0 1 2 3
// P U N E

console.log(city3[0]);
console.log(city3[1]);

let city4= "ahemdabad";
console.log(city4[0]);

//loop ===> loop

//for(intialization;condition check;increment/decrement){statement}
 
for(let i=0; i<5;i++){
    console.log(i)
};

for(let i=0;i<3;i++){
    console.log(i)
};

let city5= "wardha";
//0 1 2 3 4 5
//w a r d h a

console.log(city5.length);

for(let i=0;i<city5.length;i++){
    console.log(i)
    console.log(city5[i])
};

let city6= "japan"
 for(let i=0;i<city6.length;i++){
     console.log(city6[i])
 };

 //reverse printing
 for(let i=0;i>city6.length;i--){
     console.log(i)
 };




